development:
  adapter: pg
  database: db/development_postgresql
  pool: 5
  timeout: 5000

test:
  adapter: pg
  database: db/development_postgresql
  pool: 5
  timeout: 5000

production:
  adapter: pg
  database: db/development_postgresql
  pool: 5
  timeout: 5000
