development:
  adapter: postgresql
  database: db/development_postgresql
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: db/test_postgresql
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: blogtestdb
  username: deploy
  password: deploypassword
  hots: blog-test-db.chfsh544rna3.us-west-2.rds.amazonaws.com
  port: 5342
  pool: 20
  timeout: 5000
